// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buytjijgcqhadktjwuhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1eXRqaWpnY3FoYWRrdGp3dWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MTQzMDcsImV4cCI6MjA3MDM5MDMwN30.LJCISg8u8YSg8Cqe-B-fJlsPJxhk_Zd-iLq7QG2f5QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});